platform :ios, '12.0'

use_frameworks!

target 'MarvelUIKit_Example' do
  pod 'MarvelUIKit', :path => '../'
  pod 'SwiftLint', '~> 0.39.2'

  target 'MarvelUIKit_Tests' do
    inherit! :search_paths

  end
end
