name: Code Quality
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 11.5
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app
      - name: Install pods
        run: Pod install
        working-directory: ./Example
      - name: SwiftLint
        run: exec ../.github/scripts/swiftlint.sh
        working-directory: ./Example
      - name: Testing iOS app
        run: exec ./.github/scripts/test.sh
